# Introduction to NumPy (Numerical Python)

### Importing NumPy

In [1]:
import numpy as np

### Validating NumPy installation 

In [3]:
np.__version__

'1.16.5'

### Creating an Array

In [6]:
np_array = np.array([11,43,6,12,67,18,109])

### Finding size of an Array

In [7]:
print(np_array.size)

7


### Finding the shape of an Array

In [10]:
np_matrix = np.array([(1,2,3),(11,12,13)])
print(np_matrix.shape)

(2, 3)


### Reshaping an Array

In [11]:
np_matrix = np_matrix.reshape(3,2)
print(np_matrix)

[[ 1  2]
 [ 3 11]
 [12 13]]


### Slicing an Array

In [13]:
print(np_array[0:5])

[11 43  6 12 67]


### Reversing the order of an Array

In [14]:
print(np_array[::-1])

[109  18  67  12   6  43  11]


### Finding min, max and sum of an Array

In [15]:
print(np_array.max())
print(np_array.min())
print(np_array.sum())

109
6
266


### Finding mean, variance and Standard deviation of an Array

In [16]:
print(np_array.mean())
print(np_array.var())
print(np_array.std())

38.0
1248.0
35.32704346531139
